# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MyECS_config = debug

else ifeq ($(config),release)
  MyECS_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MyECS

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MyECS:
ifneq (,$(MyECS_config))
	@echo "==== Building MyECS ($(MyECS_config)) ===="
	@${MAKE} --no-print-directory -C . -f MyECS.make config=$(MyECS_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MyECS.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MyECS"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"